# Generated by Django 3.2.7 on 2022-03-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
