# Generated by Django 3.2.7 on 2022-03-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_maincategory_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='date',
        ),
    ]
